-include ../Makefile

create: ## run create
	$(call gcc,$(CURRENT_DIR)/create.c)
	cp $(PROJECT_ROOT)/bin/main $(PROJECT_ROOT)/bin/psem_create

unlink: ## run unlink
	$(call gcc,$(CURRENT_DIR)/unlink.c)
	cp $(PROJECT_ROOT)/bin/main $(PROJECT_ROOT)/bin/psem_unlink
