-include ../Makefile

fork: ## run fork
	$(call gcc,$(CURRENT_DIR)/fork.c)
	$(call exec)

sharing: ## run sharing
	$(call gcc,$(CURRENT_DIR)/sharing.c)
	$(call exec)

first: ## run first
	$(call gcc,$(CURRENT_DIR)/first.c)
	$(call exec, 3)
