-include ../Makefile

create: ## run create
	$(call gcc,$(CURRENT_DIR)/create.c)
	cp $(PROJECT_ROOT)/bin/main $(PROJECT_ROOT)/bin/pshm_create

write: ## run write
	$(call gcc,$(CURRENT_DIR)/write.c)
	cp $(PROJECT_ROOT)/bin/main $(PROJECT_ROOT)/bin/pshm_write
