-include ../Makefile

mem: ## run mem
	$(call gcc,$(CURRENT_DIR)/mem.c)
	$(call exec)

necho: ## run necho
	$(call gcc,$(CURRENT_DIR)/necho.c)
	make run

display_env: ## run display_env
	$(call gcc,$(CURRENT_DIR)/display_env.c)
	$(call exec)
