-include ../Makefile

unthreadsafe: ## run unthreadsafe
	$(call gcc,$(CURRENT_DIR)/unthreadsafe.c)
	$(call exec)

tsd: ## run tsd
	$(call gcc,$(CURRENT_DIR)/tsd.c)
	$(call exec)

tls: ## run tls
	$(call gcc,$(CURRENT_DIR)/tls.c)
	$(call exec)
