-include ../Makefile

pipe: ## run pipe
	$(call gcc,$(CURRENT_DIR)/pipe.c)
	$(call exec,'This is a pen. This is an apple.')

sync: ## run sync
	$(call gcc,$(CURRENT_DIR)/sync.c)
	$(call exec,2 4 6)

lswc: ## run lswc
	$(call gcc,$(CURRENT_DIR)/lswc.c)
	$(call exec)

glob: ## run glob
	$(call gcc,$(CURRENT_DIR)/glob.c)
	$(call exec)
